name: myworkwolfow
#trigger
on:
 push:
   branches:
     - main

#jobs or actions 
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: printing hello word
        run: echo "hi youness dalal"
      - name: listing all files
        run: ls -la
        

      
      
